### ISSUE TITLE
Wrong Hotkey

### ISSUE THREAD

**Issue by sebastianludwig** [wokalski/Distraction-Free-Xcode-plugin#44] opened 2015-09-28 12:40 UTC
The menu item shows `ctrl+shift+cmd+Z` as hotkey. However, I've to press `ctrl+shift+cmd+Y` to activate the distraction free mode.

**Comment by wokalski** [comment] 2015-09-28 12:54
It has probably something to do with your local settings. Isn't your keyboard `QWERTZ`?

**Comment by sebastianludwig** [comment] 2015-09-28 12:58
Yes. Well it's a custom keyboard layout, based on the U.S. layout and I swapped Z and Y.

**Comment by wokalski** [comment] 2015-09-28 12:59
Ah, Ok. Could you click the `View` menu and look up the shortcut there?

**Comment by sebastianludwig** [comment] 2015-09-28 13:02
That reads `ctrl+shift+cmd+Z`.

**Comment by wokalski** [comment] 2015-09-28 13:04
I get it. How did you create the "custom layout"? Did you use Karabiner or something similar? If yes then the issue is that the system thinks you use US layout, therefore there would be Z in this place.

**Comment by sebastianludwig** [comment] 2015-09-28 13:10
I used [Ukelele](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele) to create a true keyboard layout. I put it in my [Dropbox](https://dl.dropboxusercontent.com/u/4701827/U_S_uki_keylayout.zip in) in case you want to try.

**Comment by wokalski** [comment] 2015-09-28 13:11
It's the same issue basically and I cannot help here. The system thinks you use the US layout. Closing.

**Closed as completed by wokalski** 2015-09-28 13:11 UTC

**Comment by sebastianludwig** [comment] 2015-09-28 13:17
Shouldn't `cmd+Z` to Undo be mapped wrongly then, too?

**Comment by wokalski** [comment] 2015-09-28 13:30
I switched to German layout for a minute (I know Y and Z are swapped there too) and I got the following behavior:
1. When I undo I have to click `cmd+Y` (it is Z in the current layout)
2. When I enter the distraction free mode I have to click `cmd+shift+ctrl+Y` (also Z in the current layout)

**Comment by wokalski** [comment] 2015-09-28 13:54
@sebastianludwig the important thing though is that OS X tells me to click Z (wrong). My final thesis is that it's hardware related **or** completely messed up. I'd suggest to file a radar. If I still don't understand something don't hesitate to explane it to me.
